import fs from "fs";

export function generateMockFiles() {

  fs.writeFileSync(
    "CHANGELOG.md",
`# Changelog

## Features
- Mock payment integration

## Fixes
- Mock JWT fix
`
  );

  fs.writeFileSync(
    "RELEASE_NOTES.md",
`# Release Notes

This is a mock release generated by ReleasePilot.
`
  );
}